"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-57ep70o91f$)@y*v8pc7l=1(w&(stt4p5#-qv-$-=h%16pe&ct'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['northern-meditech-app.onrender.com',
    'localhost',
    '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- ADD THESE 3 LINES ---
    'catalog',         # Your application (Products & RFQs)
    'rest_framework',  # The API toolkit
    'corsheaders',     # The tool to fix the connection error
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <--- ADD THIS LINE AT THE TOP!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Add these new lines ---
    'catalog',             # Your App
    'rest_framework',      # The API Tool
    'corsheaders',         # The Security Tool for Frontend connection
]
# --- CORS CONFIGURATION ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
import os # <--- Add this line if 'os' is not imported at the top

# ... existing code ...

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Media Files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# --- EMAIL CONFIGURATION (Development) ---
# This prints emails to your VS Code Terminal so you can test without passwords.
# backend/config/settings.py

# ... bottom of the file ...

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kibetalex907@gmail.com' # Your Gmail address
EMAIL_HOST_PASSWORD = 'zqfb kcyz bqrp orka'     # <--- PASTE THE 16-CHAR CODE HERE
import os
import dj_database_url

# ... your other settings ...

# This looks for the DATABASE_URL environment variable. 
# If it doesn't find it (e.g., on your local machine), it defaults back to sqlite.
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}
# 1. Add to ALLOWED_HOSTS so Django accepts requests directed at your Render URL
ALLOWED_HOSTS = ['northern-meditech-app.onrender.com', 'localhost', '127.0.0.1']

INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'corsheaders',           # <-- Make sure this is here
'northernmeditech_app',         # (e.g., 'shop' or 'products')
'rest_framework',        # (If you are using Django REST Framework)
]

MIDDLEWARE = [
       'corsheaders.middleware.CorsMiddleware',  # <-- This must be at the very top
       'django.middleware.security.SecurityMiddleware',
       'django.contrib.sessions.middleware.SessionMiddleware',
       'django.middleware.common.CommonMiddleware',
       # (keep the rest of your normal middleware here)
   ]
CORS_ALLOWED_ORIGINS = [
    "https://your-frontend-url.com", 
    "http://localhost:3000", # If you are testing locally
]

# Alternatively, if you just want to open it completely for testing right now:
# CORS_ALLOW_ALL_ORIGINS = True


